<?php
    require_once "templates/layout/header.phtml";
    require_once "app/controllers/clubes.controller.php";
    $controller=new ClubesController($this->user);
?>

    <div class="container textx-center">
    
<?php
    foreach($disciplinas as $disciplina) :
    $object=$controller->obtenerClubById($disciplina->id_club); 
    $club=$object->club;
?>

        <ul class="list-group list-group-horizontal mx-5 mt-2">
            <li class="list-group-item fw-semibold "><a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-info-emphasis " 
            href="Disciplinas/<?php echo $disciplina->id_club ?>"><?php echo "Club " . $club ?></a></li>
            <li class="list-group-item fst-italic" ><?php echo $disciplina->deporte ?></li>
            <li class="list-group-item fst-italic"><?php echo $disciplina->direccion ?></li>
            <li class="list-group-item fst-italic"><?php echo $disciplina->contacto ?></li>
            <?php if($this->user) : ?>
                <div class="actions mx-3">
                    <a href="eliminarDisciplina/<?php echo $disciplina->id_disciplina ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar</a>
                </div>
                <div class="actions">
                    <a href="Editar/Disciplina/<?php echo $disciplina->id_disciplina ?>" type="button" class='btn btn-primary btn-sm ml-auto'>Editar</a>
                </div>
            <?php endif; ?>    
        </ul>

    
<?php
    endforeach ;
    require_once "templates/layout/footer.phtml";
?>
    </div>