<?php
    require_once "templates/layout/header.phtml";
    require_once "app/controllers/clubes.controller.php";
    $controller=new ClubesController();
    $object=$controller->obtenerClubById($id); 
    $club=$object->club;
?>
    <div class="container textx-center">
    <h3 class="mx-5 mt-2 fst-italic text-body-tertiary"><?php echo "Club ". $club ?></h3>;
<?php
    foreach($disciplinasByClub as $disciplina) :
?>

         <ul class="list-group list-group-horizontal mx-5 ">
            <li class="list-group-item fst-italic" ><?php echo $disciplina->deporte ?></li>
            <li class="list-group-item fst-italic"><?php echo $disciplina->direccion ?></li>
            <li class="list-group-item fst-italic"><?php echo $disciplina->contacto ?></li>
        </ul>

<?php
    endforeach ;
    require_once "templates/layout/footer.phtml";
?>
    </div>