<?php
    require_once "templates/layout/header.phtml";?>

    <?php if ($error): ?>
        <div class='alert alert-danger text-center' role='alert'>
            <?= $error ?>
        </div>
    <?php endif ?>

<div class=" d-flex justify-content-center align-items-center vh-100">

    <div class="bg-white p-5 rounded-5 text-secondary shadow" style="width: 25rem">

      <div class="d-flex justify-content-center">
        <img src="templates/layout/img/usuario.png" alt="login-icon" style="height: 7rem"/>
      </div>

      <div class="text-center fs-1 fw-bold">Iniciar Sesion</div>

    <form action="Login" method="post">
      <div class="input-group mt-4">
        <input class="form-control bg-light text-center" type="text"  placeholder="Email" name="email" required/>
      </div>

      <div class="input-group mt-1">
        <input class="form-control bg-light text-center" type="password" placeholder="Password" name="password" required/>
      </div>

      <button class="btn btn-info text-white w-100 mt-4 fw-semibold shadow-sm" type="submit">Login</button>
    </form>

      <div class="d-flex gap-1 justify-content-center mt-1">
        <div>No tienes cuenta?</div>
        <a href="#" class="text-decoration-none text-info fw-semibold">Registrate</a>
      </div>

    </div>

</div>
<?php
    require_once "templates/layout/footer.phtml";
?>