<?php require_once "templates/layout/header.phtml" ?>

<main class="container mt-3">

    <h3 class="mt-4 fst-italic text-body-tertiary">Inserte un club </h3>
        <form action="insertarClub" method="POST" class="my-4">
            <div class="row">
                <div class="col-5">
                    <div class="form-group">
                        <label>Club</label>
                        <input required name="club" type="text" class="form-control">
                    </div>
                </div>

                <div class="col-5">
                    <div class="form-group">
                        <label>Localidad</label>
                        <input type="text" required name="localidad" class="form-control">
                    </div>
                </div>

                <div class="col-2">
                    <div class="form-group">
                        <label>Fundacion</label>
                        <input type="date" required name="fundacion" class="form-control">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-5">
                    <div class="form-group">
                        <label>Sede</label>
                        <input required name="sede" type="text" class="form-control">
                    </div>
                </div>

                <div class="col-3">
                    <div class="form-group">
                        <label>Contacto</label>
                        <input type="number" required name="contacto" class="form-control">
                    </div>
                </div>

                <div class="col-2">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary mt-4">Guardar</button>
                    </div>
                </div>
            </div>
        </form>


    <h3 class="mt-5 fst-italic text-body-tertiary">Inserte un socio </h3>
    <form action="insertarSocio" method="POST" class="my-4">
        <div class="row">

            <div class="col-5">
                <div class="form-group">
                    <label>Nombre</label>
                    <input required name="nombre" type="text" class="form-control">
                </div>
            </div>

            <div class="col-5">
                <div class="form-group">
                    <label>Apellido</label>
                    <input type="text" required name="apellido" class="form-control">
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-3">
                <div class="form-group">
                    <label>DNI</label>
                    <input type="number" required name="dni" class="form-control">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label>Club Asociado</label>
                    <select required name="id_club" class="form-control">
                        <?php foreach($clubes as $club): ?>
                        <option value="<?php echo $club->id_club ?>"><?php echo $club->club ?></option>
                        <?php endforeach; ?>
                        </select>
                </div>
            </div>

            <div class="col-2">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary mt-4">Guardar</button>
                </div>
            </div>

        </div>
    </form>


    <h3 class="mt-5 fst-italic text-body-tertiary">Inserte una disciplina </h3>
    <form action="insertarDisciplina" method="POST" class="my-4">
        <div class="row">

            <div class="col-5">
                <div class="form-group">
                    <label>Deporte</label>
                    <input required name="deporte" type="text" class="form-control">
                </div>
            </div>

            <div class="col-5">
                <div class="form-group">
                    <label>Direccion</label>
                    <input type="text" required name="direccion" class="form-control">
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label>Contacto</label>
                    <input type="number" required name="contacto" class="form-control">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label>Club Asociado</label>
                    <select required name="id_club" class="form-control">
                        <?php foreach($clubes as $club): ?>
                        <option value="<?php echo $club->id_club ?>"><?php echo $club->club ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="col-2">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary mt-4">Guardar</button>
                </div>
            </div>
            
        </div>
    </form>
    
</main>

<?php require_once "templates/layout/footer.phtml" ?>
