<?php $año=new DateTime()?>
<!DOCTYPE html> 
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Clubes</title>
</head>
<body>


    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <h1><a class="navbar-brand fs-2 fw-bold opacity-75" href="inicio">Clubes</a> </h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mx-2" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active fs-4 mx-2  focus-ring focus-ring-primary py-1 px-1 text-decoration-none border rounded-3" aria-current="page" href="inicio">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 mx-2  focus-ring focus-ring-primary py-1 px-1 text-decoration-none border rounded-3" href="socios">Socios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 mx-2  focus-ring focus-ring-primary py-1 px-1 text-decoration-none border rounded-3" href="disciplinas">Disciplinas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 mx-2  focus-ring focus-ring-primary py-1 px-1 text-decoration-none border rounded-3" href="insertar">Insertar</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>